// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231213082422_dbcontexone")]
    partial class dbcontexone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.EnglishExamContent", b =>
                {
                    b.Property<int>("EnglishExamContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnglishExamContentID"));

                    b.Property<string>("EnglishExamCorrect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishExamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishExamOptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishExamOptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishExamOptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishExamOptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishStoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnglishExamContentID");

                    b.ToTable("EnglishExamContents");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EnglishLessonContent", b =>
                {
                    b.Property<int>("EnglishLessonContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnglishLessonContentID"));

                    b.Property<string>("EnglishLessonContentFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLessonContentSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLessonContentThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLessonImagUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLessonTitleFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLessonTitleSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLessonTitleThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishTopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnglishLessonContentID");

                    b.ToTable("EnglishLessonContents");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EnglishStory", b =>
                {
                    b.Property<int>("EnglishStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnglishStoryID"));

                    b.Property<string>("EnglishStoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishStoryImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishStoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnglishStoryID");

                    b.ToTable("EnglishStroies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EnglishStoryDetails", b =>
                {
                    b.Property<int>("EnglishStoryDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnglishStoryDetailsID"));

                    b.Property<string>("EnglishStoryDetailsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishStoryDetailsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishStoryImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnglishStoryDetailsID");

                    b.ToTable("EnglishStoryDetails");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EnglishTopic", b =>
                {
                    b.Property<int>("EnglishTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnglishTopicID"));

                    b.Property<string>("EnglishTopicDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishTopicImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishTopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnglishTopicID");

                    b.ToTable("EnglishTopics");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EnglishVocabulary", b =>
                {
                    b.Property<int>("EnglishVocabularyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnglishVocabularyID"));

                    b.Property<string>("EnglishPronunciation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurkishWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnglishVocabularyID");

                    b.ToTable("EnglishVocabularies");
                });

            modelBuilder.Entity("EntityLayer.Concrete.FrenchStory", b =>
                {
                    b.Property<int>("FrenchStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrenchStoryID"));

                    b.Property<string>("FrenchStoryImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenchStroyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenchStroyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FrenchStoryID");

                    b.ToTable("FrenchStories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SpanishExamContent", b =>
                {
                    b.Property<int>("SpanishExamContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpanishExamContentID"));

                    b.Property<string>("SpanishExamCorrect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishExamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishExamOptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishExamOptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishExamOptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishExamOptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpanishExamContentID");

                    b.ToTable("SpanishExamContents");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SpanishStory", b =>
                {
                    b.Property<int>("SpanishStoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpanishStoryID"));

                    b.Property<string>("SpanishStoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishStoryImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishStoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpanishStoryID");

                    b.ToTable("SpanishStories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SpanishStoryDetail", b =>
                {
                    b.Property<int>("SpanishStoryDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpanishStoryDetailID"));

                    b.Property<string>("SpanishStoryDetailsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishStoryDetailsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishStoryImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpanishStoryDetailID");

                    b.ToTable("spanishStoryDetails");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SpanishTopic", b =>
                {
                    b.Property<int>("SpanishTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpanishTopicID"));

                    b.Property<string>("SpanishTopicDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishTopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpanishTopicID");

                    b.ToTable("SpanishTopics");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SpanishWords", b =>
                {
                    b.Property<int>("SpanishWordsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpanishWordsID"));

                    b.Property<string>("EnglishWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurkishWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpanishWordsID");

                    b.ToTable("SpanishWords");
                });
#pragma warning restore 612, 618
        }
    }
}
